### ISSUE TITLE
Kein Problem

### ISSUE THREAD

**Issue by Tombo89** [jstiefel/esp32_komoot_ble#2]
Hallo,
gleich vorweg, ich habe kein Problem, wusste aber nicht wie ich sonst kontakt aufnehmen kann.

Ich finde es interessant was du hier geschafft hast. Ich habe vor c.a 1,5 Jahren das gleiche gebaut, doch habe es nie so richtig mit der Bluetooth kommunikation hinbekommen. Ich denke ich werde mir mal deinen code genauer ansehen, da kann ich bestimmt noch was lernen.

Was ich gesehen habe ist das du ein Oled display nutzt. Hattest du bisher damit Probleme bei Sonneneinstrahlung? Ich habe nämlich darmals festegestellt das es bei Sonne nicht wirklich gut lesbar ist und extra high brightness sunlight readable tfts bestellt.

Da es die in den kleinen größen nur bei Digikey gab habe ich um versand zu sparen mehrere bestellt. Wenn du Interesse hast würde ich dir zum testen mal eins abgeben. Die ansteuerung mit dem Esp ist ziemlich simpel und funktioniert ohne Probleme.

Vielen dank schonmal für das veröffentlichen des Codes, den werde ich jetzt erstmal studieren :)

**Comment by jstiefel** [comment]
Hallo

Danke! In BLE muss man sich in der Tat ein bisschen einarbeiten. Wichtig ist halt, dass die Hardware den BLE Standard auch unterstützt. Damit fallen etwa die Arduino HC-05/ HC-06 Module sowieso schon aus dem Rennen. Der ESP32 bietet da eine gute Alternative. Aber gerade Ende letzten Jahres war die entsprechende Library auch noch stark in der Entwicklungsphase und es würde mich nicht verwundern, wenn mit der aktuellen Version mein Code nicht mehr läuft. Da wurde schon damals sehr viel geändert. Also unbedingt zum testen die entsprechende Version verwenden.

Habe das OLED Display nicht weiter getestet. Auf jedenfall interessant wäre auch ein E-Ink Display. Du darfst halt die Akku-Laufzeit nicht vergessen. Das könnte vielleicht bei "extra high brightness" zum Problem werden.

Viel Erfolg!
