### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by coltc50** [jstiefel/esp32_komoot_ble#3]
Hello, great thing you made here. I just ordered all the things and will try to build it. I don't have experience with adafruit at the moment. I just using a lot of arm platines like raspberry or odroid. This thing is new for me. Hope I will get it to work.

Now my question. You maintain this project anymore or is it dead?

I wish a little smaller case but I had the problem that I didn't have a 3d printer.

I will try first to make it working and then I look how I get build a nice case.

Thank you for this great project. It's that what I searched and waiting for so long.

**Comment by jstiefel** [comment]
Hi,

Thank you. I currently don't have time to maintain this project. But if you use the versions as mentioned in the Readme, it should still work. Feel free to contribute your model/ code if you want.

**Comment by coltc50** [comment]
Thank you. Now I have everything here SD1306 and a ESP32 Feather Board. But I don't know how to start and how to upload your code to the ESP32. Can you give me a hint?

**Comment by coltc50** [comment]
Oh hab jetzt erst gesehen das Du auch Deutsch kannst.

Also ich habe es jetzt zumindest mal auf den ESP32 bekommen, aber wenn ich es ausführe und mich verbinde stürzt es ab:

21:41:17.925 -> Wake up!
21:41:17.925 -> Starting Arduino BLE Client application...
21:41:18.535 ->  - Created client
21:41:18.628 -> BLE Advertised Device found: Name: , Address: 3a:9d:15:ad:6f:e8, manufacturer data: 0600010920029f78d337bcfc6c35786a98772a89b35c6295ec36af358a
21:41:18.675 -> BLE Advertised Device found: Name: HUAWEI Mate 9, Address: xx:xx:xx:xx:xx:xx, serviceUUID: safsf-safds-asdfaf-asdfadf-asdfasf
21:41:18.675 -> Found our device!
21:41:18.675 -> Forming a connection to 62:ee:51:30:eb:c0
21:41:18.956 -> onConnect callback: Connected
21:41:18.956 ->  - Connected to server
21:41:19.753 ->  - Found our service
21:41:19.753 ->  - Found our characteristic
21:41:19.753 -> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
21:41:19.753 -> Core 1 register dump:
21:41:19.753 -> PC      : 0x400d6647  PS      : 0x00060530  A0      : 0x800d1aad  A1      : 0x3ffc8980  
21:41:19.753 -> A2      : 0x00000000  A3      : 0x3ffbed90  A4      : 0x00000002  A5      : 0x00000001  
21:41:19.753 -> A6      : 0x3ffe0be4  A7      : 0x3f018a00  A8      : 0x800d5d38  A9      : 0x3ffc8930  
21:41:19.753 -> A10     : 0x3ffc897c  A11     : 0xc2cfe5f0  A12     : 0x3ffc6338  A13     : 0xc2cfe5f0  
21:41:19.800 -> A14     : 0x00000001  A15     : 0x00000038  SAR     : 0x00000018  EXCCAUSE: 0x0000001c  
21:41:19.800 -> EXCVADDR: 0x00000030  LBEG    : 0x4000c349  LEND    : 0x4000c36b  LCOUNT  : 0x00000000  
21:41:19.800 -> 
21:41:19.800 -> Backtrace: 0x400d6647:0x3ffc8980 0x400d1aaa:0x3ffc89b0 0x400d1def:0x3ffc8a00 0x400d1eb3:0x3ffc8a20 0x400d3227:0x3ffc8a60 0x400da40f:0x3ffc8ab0 0x4008e539:0x3ffc8ad0
21:41:19.800 -> 
21:41:19.800 -> Rebooting...

**Comment by coltc50** [comment]
Ich bekomme deine Libarys nicht in IDE. Unter den Links finde ich auch nicht die RC1 Version.
Ich werde heute Abend einfach Mal mit einem älteren Libary versuchen.

**Comment by jstiefel** [comment]
https://github.com/espressif/arduino-esp32/tree/1.0.1-rc1

But it would make sense to adapt to the new release. I just sticked to this version because back then, many changes were going on.

Since the other questions are more general, I would recommend to read into some ESP32 and Arduino tutorials. BLE is not the easiest thing to start with...

**Comment by coltc50** [comment]
Ok, thank you to pointing me to it. I manage to load the 1.0.1-rc1 and to change the commit like its explained on the readme but the guru mediation stays:

22:02:12.571 -> Starting Arduino BLE Client application...
22:02:13.192 ->  - Created client
22:02:13.261 -> BLE Advertised Device found: Name: HUAWEI Mate 9, Address: xx:xx:xx:xx:xx, serviceUUID: asd-asd-asd-asd-asd-asd-asd
22:02:13.261 -> Found our device!
22:02:13.261 -> Forming a connection to 6a:52:fe:9e:c5:48
22:02:13.261 -> [I][BLEDevice.cpp:600] addPeerDevice(): add conn_id: 0, GATT role: client
22:02:13.261 -> [W][Connection.cpp:166] my_gattc_event_handler(): custom gattc event handler, event: 0
22:02:13.811 -> [W][Connection.cpp:166] my_gattc_event_handler(): custom gattc event handler, event: 40
22:02:13.811 -> onConnect callback: Connected
22:02:13.811 ->  - Connected to server
22:02:13.811 -> [W][Connection.cpp:166] my_gattc_event_handler(): custom gattc event handler, event: 2
22:02:14.598 -> [W][Connection.cpp:166] my_gattc_event_handler(): custom gattc event handler, event: 7
22:02:14.598 -> [W][Connection.cpp:166] my_gattc_event_handler(): custom gattc event handler, event: 7
22:02:14.598 -> [W][Connection.cpp:166] my_gattc_event_handler(): custom gattc event handler, event: 7
22:02:14.598 -> [W][Connection.cpp:166] my_gattc_event_handler(): custom gattc event handler, event: 7
22:02:14.598 -> [W][Connection.cpp:166] my_gattc_event_handler(): custom gattc event handler, event: 7
22:02:14.598 ->  - Found our service
22:02:14.598 -> [W][Connection.cpp:166] my_gattc_event_handler(): custom gattc event handler, event: 6
22:02:14.668 -> [WGuru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
22:02:14.668 -> Core 1 register dump:
22:02:14.668 -> PC      : 0x400d6f93  PS      : 0x00060530  A0      : 0x800d1d79  A1      : 0x3ffc99b0  
22:02:14.668 -> A2      : 0x00000000  A3      : 0x3ffbed90  A4      : 0x00000002  A5      : 0x00000001  
22:02:14.668 -> A6      : 0x3ffe22b4  A7      : 0x3f019a30  A8      : 0x800d65a4  A9      : 0x3ffc9960  
22:02:14.668 -> A10     : 0x3ffc99ac  A11     : 0x3ffe22b4  A12     : 0x00000024  A13     : 0xbbc909ee  
22:02:14.668 -> A14     : 0x3ffc9960  A15     : 0x00000038  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
22:02:14.703 -> EXCVADDR: 0x00000030  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  
22:02:14.703 -> 
22:02:14.703 -> Backtrace: 0x400d6f93:0x3ffc99b0 0x400d1d76:0x3ffc99e0 0x400d20bb:0x3ffc9a30 0x400d2197:0x3ffc9a50 0x400d350b:0x3ffc9a90 0x400db77b:0x3ffc9ae0 0x4008e5c9:0x3ffc9b00
22:02:14.703 -> 
22:02:14.703 -> Rebooting...
22:02:14.703 -> ets Jun  8 2016 00:22:57
22:02:14.703 -> 
22:02:14.703 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
22:02:14.703 -> configsip: 0, SPIWP:0xee
22:02:14.703 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
22:02:14.703 -> mode:DIO, clock div:1
22:02:14.703 -> load:0x3fff0018,len:4
22:02:14.703 -> load:0x3fff001c,len:1100
22:02:14.703 -> load:0x40078000,len:9564
22:02:14.703 -> ho 0 tail 12 room 4
22:02:14.703 -> load:0x40080400,len:6348
22:02:14.703 -> entry 0x400806a8

What can I do?

**Comment by coltc50** [comment]
Now I also import the mention ssd1306 library in the readme and tried with old komoot version. Problem stays. I'm out of ideas... what I'm doing wrong?

**Comment by jstiefel** [comment]
It‘s clearly a BLE problem. You should try to debug by adding serial outputs to the code and find the line where it fails. I honestly never tried with Android.

My recommendation is still to update the BLE library since back then this was a little bit tricky and now it‘s probably much better documented and improved.

Otherwise, if you have a specific error, the developers of the BLE library are normally answering very quickly.

**Comment by coltc50** [comment]
Thank you. I tried with my father's iPhone and this works. Seems a android thing... I will ask in the community for help. Thank you again for your help.

**Comment by coltc50** [comment]
Ok. chegewara from nkolban/esp32-snippets github did found solution for android. 
Comment out `//pRemoteCharacteristic->getDescriptor(BLEUUID((uint16_t)0x2902))->writeValue((uint8_t*)notificationOn, 2, true);` in connection.ccp

And then in the ble library comment out `if(desc != nullptr)
			desc->writeValue(val, 2);` in BLERemoteCharacteristic.ccp

Just for everybody try to use this on android like me...

But attention. With this change you break IOS.

**Comment by jstiefel** [comment]
Cool, thanks for the hint!

**Comment by thefriedc** [comment]
Hi, @coltc50  - What is your connection workflow for the ESP32 and Komoot?
Is there really a need to pair with your Android system? And then? Is there also something you must do in the Komoot app additionally?
My Problem is, I cannot discover the Komoot BLE service at all. Not even with 3rd Party BLE scanner apps.

Cheers, Chris

**Comment by coltc50** [comment]
@thefriedc No you haven't to pair with your phone. But you have to make the changes I mention to connect with a android phone. When you have made the change you can't connect to Iphone anymore. Keep this in mind.

So then you fire up your arduino to search for bluetooth and then you start komoot going to your profile, then settings and then to bluetooth connect and choose "FLYER E-Bike". Now it should connect. You can now go out to start a navigate and it will show on your arduino.

**Comment by thefriedc** [comment]
OK - thanks a lot! I will give that a try as soon as possible.

How did you know to choose "FLYER E-Bike"?

**Comment by coltc50** [comment]
Did forget where I read it. It was mentioned somwhere on the net. I read your other messages on the other git with kernel panic. Did you changed the ble files like I said before? Without the changes it doesn't work.

Here my post in the ble library explained how to change for android.

https://github.com/nkolban/esp32-snippets/issues/902

**Comment by thefriedc** [comment]
Actually, I use Arduino IDE and the BLE library is included in the core
libs there - v 1.0.2
I could not find the lines of code there you mentioned.
My stacktrace is other one as yours. Also BLERemotedescriptor but in the
Method "writeValue".

**Comment by thefriedc** [comment]
PC: 0x400d4a67: BLERemoteDescriptor::writeValue(unsigned char*, unsigned int, bool) at /Users/chris/Library/Arduino15/packages/esp32/hardware/esp32/1.0.2/libraries/BLE/src/BLERemoteDescriptor.cpp line 131
EXCVADDR: 0x00000030

Decoding stack results
0x400d4a67: BLERemoteDescriptor::writeValue(unsigned char*, unsigned int, bool) at /Users/chris/Library/Arduino15/packages/esp32/hardware/esp32/1.0.2/libraries/BLE/src/BLERemoteDescriptor.cpp line 131
0x400d43cb: BLERemoteCharacteristic::registerForNotify(void (*)(BLERemoteCharacteristic*, unsigned char*, unsigned int, bool), bool) at /Users/chris/Library/Arduino15/packages/esp32/hardware/esp32/1.0.2/libraries/BLE/src/BLERemoteCharacteristic.cpp line 472
0x400d182d: connectToServer(BLEAddress) at /Users/chris/Documents/Arduino/komoot_nav/komoot_nav.ino line 135
0x400d18f2: loop() at /Users/chris/Documents/Arduino/komoot_nav/komoot_nav.ino line 204
0x400d8a51: loopTask(void*) at /Users/chris/Library/Arduino15/packages/esp32/hardware/esp32/1.0.2/cores/esp32/main.cpp line 19
0x4008e425: vPortTaskWrapper at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/port.c line 143

**Comment by linusheck** [comment]
I also have this problem, so I created a pull request (issue substitute) in the repository.

**Comment by coltc50** [comment]
Now I seem to have the same problem. The connection does work only sometimes. Didn't know what happened. I tried to start from beginning but can't get it to stable. Didn't know if it was a update. Will try and report back if I found the culprit.

**Comment by linusheck** [comment]
> Now I seem to have the same problem. The connection does work only sometimes. Didn't know what happened. I tried to start from beginning but can't get it to stable. Didn't know if it was a update. Will try and report back if I found the culprit.

Did you manage to get any callbacks working? If so, can you please tell me what you did? :)
For me it also only connects on the second try every time.

**Comment by linusheck** [comment]
Oh, so this is what Komoot said about this:

> Based on my current knowledge we'll put this into our list of things we'll look into when we do a next iteration on the protocol.
> For sure we want the interface being able to be used by as many BLE devices as possible. Adding the descriptor seems to make our interface more compatible to other libraries out there and will most probably an easy thing to for us and most probably will not break the functionality of existing devices using it. But this is something we have to make sure first.

**Comment by coltc50** [comment]
@glatteis Great to read from komoot. Will hope that they don't need so much time to Implement it.

Yes here also only on the second try. I think something must update between. In begin of september it worked for me without problems.  If I could find what changes till now?

I'm working all the weeks on a new version with 2 displays, rtc timeclock with temperature sensor and a automated switch on. Now I want to integrate the komoot ble thing and it didn't work anymore... What a mess...

**Comment by coltc50** [comment]
Ok I found my problem. I had an old library in my data. Deleted all ble librarys and only edit the one in hardware esp32 and now everything is working again.

Great!

**Comment by kriszhn** [comment]
guys my app gets connected it sometimes restart and doesn't show any data in the screen.please help me
