### ISSUE TITLE
Komoot BLE Service not found

### ISSUE THREAD

**Issue by thefriedc** [jstiefel/esp32_komoot_ble#4]
Hi @jstiefel,

thanks for sharing your project. I had the same idea with an ESP and display laying around at home. After some googling, I found your project.

I got a question according the BLE service scan and am hoping that you can help me out. I am having troubles discovering the Komoot service.

Also when using your code, the ESP32 does not find the Komoot BLE Service.
So my question:
In the Video you use an iPhone. Did you also test your thingy with an Android device?
Did you need to pair your device in the Android settings and was there something you had to configure in the Komoot app for making this work?

I would be really grateful if you could point me in some direction.

Cheers Chris

**Comment by jstiefel** [comment]
Hi Chris,

I never tried with an Android phone. But someone just did and here you can find a solution:
https://github.com/jstiefel/esp32_komoot_ble/issues/3#issuecomment-530089381

I'm not sure how this works for Android, but for iPhone there is no need to pair outside the Komoot app (actually, you can't).

Hope this helps!

**Comment by thefriedc** [comment]
Thanks a lot for the fast reply!

I mentioned the guy from #3 in a new comment on the issue. Hopefully he can point out the Android specifics with connecting.

Thanks, Chris

**Comment by jstiefel** [comment]
Did you take a look at this:

https://github.com/komoot/BLEConnect#pairing-on-android-not-ios

**Comment by thefriedc** [comment]
Yes, thanks - the very first thing I read ;)
 The Problem is, that when creating just a BLE client, my Android device cannot even find the ESP32 for pairing. 
Also tried with another paired Android device and BLE Scanner app. No Komoot BLE service discovered.
