### ISSUE TITLE
Main code 

### ISSUE THREAD

**Issue by kriszhn** [jstiefel/esp32_komoot_ble#5]
Hello bro after a lot of search found ur code. But I am not able to find main code that is  .ino file to run. Please help me

**Comment by jstiefel** [comment]
```
Rename main file in .ino to work with Arduino IDE
```
In the hints ;-). But I assume my code will not work anymore if you don't exactly use the mentioned libraries. The official library supports BLE now. Need to rewrite this once I have time.

**Comment by kriszhn** [comment]
Yeah bro as in home quarantine.. Was fully trying to understand ur program.. Can you give Me some more hints. I will make them.. It displays picture connects to app. But I am not able to see data transfered from app. Please help me bro.

**Comment by daveharix** [comment]
I also was trying to get this project running. 
there are some little problems with the new BLE libraries, and this Project is running with the old libraries. I found a similar Project that’s running fine: https://github.com/RpDp-git/komoot-eink-navigator

**Comment by kriszhn** [comment]
@daveharix  thank you bro after 3 months i found and it worked very well.. thanks again bro
