### ISSUE TITLE
Hat Komoot etwas geändert? bekomme leider Keine Verbindung Hergestellt zur App (IOS)

### ISSUE THREAD

**Issue by daveharix** [jstiefel/esp32_komoot_ble#6]
Hey, 
ich hoffe es ist ok für Sie, wenn ich auf Deutsch schreibe. 
Ich bin seit längerem auf der Suche nach einer Navigationsanzeige mittels ESP32. Zuletzt habe ich mich mit einem ähnlichen Projekt auseinandergesetzt. https://github.com/alexanderlavrushko/BLE-HUD-navigation-ESP32 
Dort ist auch eine BLE Kommunikation mit einer Navigations App. Das Ganze lief auch super auf dem ESP32. 
Leider wird die App dort nach 7 Tage auf Basisbetrieb umgestellt und die zusätzliche BLE Kommunikation wird eingestellt. 
Ich bin dann vor kurzem auf dieses Projekt gestoßen. Tatsächlich sind die Projekte sehr ähnlich, wodurch ich das ganze schnell auf dem ESP32 und dem I2C Display am Laufen hatte. 
Zunächst habe ich den Original Code implementiert, aber hier bekomme ich keine Verbindung zur Komoot App hergestellt. Der Code hier war doch für das Iphone gedacht, oder? Ich hatte auch ein paar Abwandlungen für Andorid hier gesehen. Leider ist mein Android Gerät zu alt und ich konnte keine Tests machen.
Zuletzt habe ich den Code von dem ersten Projekt angepasst (das lief soweit ja ganz gut mit dem Iphone und es sind keine großen Änderungen zu machen), aber selbst damit bekomme ich keine Verbindung. 
Ich finde mein Gerät aber irgendwie bekomme ich die Verbindung nicht hergestellt. Hat Komoot da vielleicht mittlerweile etwas geändert? Funktioniert der Code bei Ihnen noch? 
hier ein Kurzer Ausschnitt von meiner Ausgabe:
_
mdata OK
setup() finished
loop() start
Forming a connection to 51:88:3d:ce:48:af
 - Created client
 - Connected to server
Failed to find our service UUID: 71c1e128-d92f-4fa8-a2b2-0f171db3436c
Error: cannot connect to BLE server in background

_

Vielleicht habe Sie noch einen Tipp. 
Würde mich über eine Antwort freuen.

**Comment by daveharix** [comment]
Hey, 
nur falls hier einer auch nicht weiterkommt. Ich habe bei https://github.com/RpDp-git/komoot-eink-navigator eine kleine Weiterentwicklung gefunden. Dort steht zwar, dass es für Android gedacht ist, aber es funktioniert auch mit IOS. 
Ich habe den Code vereinfacht und erstmal eine Serial Ausgabe gemacht. 

**In der neuen Komoot App muss man einmal Aktiv die Verbindung Herstellen:** 
Profil >Einstellungen >Bluetooth Connect > Flyer E-Bike > Dort wird dann der ESP32 verbunden
Komoot zeigt bei erfolgreicher Verbindung einen Haken hinter Flyer Bike und sagt Verbunden
_(Komoot Version 10.3.8)_
Dann eine Route starten und die Kommunikation beginnt. 

```
Starting Arduino BLE Client application...
Starte SCAN
5 Sekunden
BLE Advertised Device found: Name: XXXXX
SETUP END
DO CONNECT
Forming a connection to 77:ef:1d:14:a2:3b
 - Created client
 - Connected to server
 - Found our service
 - Found our characteristic
The characteristic value was: We are now connected to the BLE Server.
Street: Weg
DIR: 2
Direction: 2
Notify callback for characteristic 503dd605-9bcb-4f6e-b235-270a57483026 of data length 4
data: ]q_p
Direction: 2
Direction: 2

```
Scheint alles zu gehen, leider habe ich immer wieder Verbindungsabbrüche, aber das ist auch noch händelbar.  
Aber Großes Lob an Sie für die ersten Entwicklungen.

**Comment by jstiefel** [comment]
Hey @daveharix 

Danke fürs Reinschauen. In der Tat sind die hier verwendeten Libraries schon älter und noch von der Zeit bevor es die offizielle ESP32 BLE Library gab. Es ist also zu erwarten, dass das Projekt so mit der neuen Library nicht mehr funktioniert. Das Komoot Protokoll ist gleich geblieben, um auch weiterhin die früheren Geräte zu unterstützen.
